<?php
return[
    'api/sign-up'=>[
        'required'=>[
            'name'=>'required',
            'email'=>'required|unique:users,email',
            //'phone'=>'required',
            'password'=>'required|min:6|confirmed',
            'device_type'=>'required',
            'device_token'=>'required'
        ],
        'optional'=>[
            'image'=>'mimes:jpeg,png,jpg,gif,bmp,svg|required',
            'user_type'=>'required',
            'grade_year'=>'required',
            'school_name'=>'required',
            'state'=>'required',
            'gpa'=>'required'
        ]
    ],
    'api/sign-in'=>[
        'required'=>[
            'email'=>'required',
            'password'=>'required|min:6',
            'device_type'=>'required',
            'device_token'=>'required',
        ],
        'optional'=>[
            'user_type'=>'required',
            'grade_year'=>'required',
            'school_name'=>'required',
            'state'=>'required',
            'gpa'=>'required'
        ]
    ],
    'api/social-login'=>[
        'required'=>[
            'name'=>'required',
            'email'=>'required',
            //'phone'=>'required',
            'device_type'=>'required',
            'device_token'=>'required'
        ],
        'optional'=>[
            'image'=>'mimes:jpeg,png,jpg,gif,bmp,svg|required',
            'fb_login_id'=>'required_without_all:google_login_id,apple_login_id',
            'google_login_id'=>'required_without_all:fb_login_id,apple_login_id',
            'apple_login_id'=>'required_without_all:fb_login_id,google_login_id',
            'user_type'=>'required',
            'grade_year'=>'required',
            'school_name'=>'required',
            'state'=>'required',
            'gpa'=>'required'
        ]
    ],
    'api/profile'=>[
        'required'=>[
        ],
        'optional'=>[
            'first_name'=>'required',
            'last_name'=>'required',
            //'email'=>'required|unique:users,email,1',
            'email'=>'required|email',
            'password'=>'required|min:6|confirmed',
            'old_password'=>'required_with:password',
            'image'=>'mimes:jpeg,png,jpg,gif,bmp,svg|required',
            'user_type'=>'required',
            'grade_year'=>'required',
            'school_name'=>'required',
            'state'=>'required',
            'gpa'=>'required'
        ]
    ],
    'api/forgot-password'=>[
        'required'=>[
            'email'=>'required'
        ],
        'optional'=>[

        ]
    ],
    'api/support'=>[
        'required'=>[
            'description'=>'required'
        ],
        'optional'=>[
            'title'=>'required'
        ]
    ],
    'api/feedback'=>[
        'required'=>[
            'feedback_text'=>'required'
        ],
        'optional'=>[
        ]
    ],
    /*****
     * Chats
     */
    'api/initiate-chat'=>[
        'required'=>[
            'to_id'=>'required'
        ],
        'optional'=>[

        ]
    ],
    'api/chat'=>[
        'required'=>[
            'conversation_id'=>'required|exists:chats',
            'message'=>'required'
        ],
        'optional'=>[

        ]
    ],
    'api/get-my-chats'=>[
        'required'=>[

        ],
        'optional'=>[

        ]
    ],
    'api/get-chat-detail'=>[
        'required'=>[
            'conversation_id'=>'required',
        ],
        'optional'=>[

        ]
    ],
    'api/add-checklist'=>[
        'required'=>[
            'name'=>'required',
            'type'=>'required',
        ],
        'optional'=>[

        ]
    ],
    'api/add-type'=>[
        'required'=>[
            'name'=>'required',
            'type'=>'required',
        ],
        'optional'=>[

        ]
    ],
    'api/update-type'=>[
        'required'=>[
            'id'=>'required',
        ],
        'optional'=>[
            'name'=>'required',
            'type'=>'required',
        ]
    ],
    'api/delete-type'=>[
        'required'=>[
            'id'=>'required',
        ],
        'optional'=>[
            
        ]
    ],
    'api/update-profile'=>[
        'required'=>[
        ],
        'optional'=>[
            'name'=>'required',
            'user_type'=>'required',
            'grade_year'=>'required',
            'school_name'=>'required',
            'state'=>'required',
            'gpa'=>'required'
        ]
    ],
    'api/add-answer'=>[
        'required'=>[
            'sub_cat_list_id'=>'required',
            'cat_question_id'=>'required',
            
        ],
        'optional'=>[
            'answer'=>'required',
        ]
    ],
];
